
export const MESSAGE_CODE = {
    NOT_FOUND: "NOT FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    BAD_REQUEST: "BAD REQUEST",
    CREATED: "CREATED",
    SUCCESS: "SUCCESS",
    INTERNAL_SERVER_ERROR: "INTERNAL SERVER ERROR"
} 
